#!/usr/bin/env python3

"""
Sample QR Generator
"""

import os
import sys

cwd = os.path.dirname(os.path.realpath(__file__))

__version__ = '1.0'

from dynacli import main

search_path = [cwd]
sys.path.extend(search_path)

main(search_path)