import shutil
from datetime import datetime
from typing import Literal, TypedDict

import requests

__version__ = "3.0"

class Vaccination(TypedDict):
    date: datetime
    manufacturer: Literal["pfizer", "moderna", "astrazeneca", "janssen", "sinovac"]


class QRCode(TypedDict):
    name: str
    birth: str
    vaccination: list[Vaccination]


def generate(first_name: str, last_name: str, birthdate: str,  **vaccination: str) -> None:
    """
    Generate your vaccination QR code.

    Args:
        first_name (str): name of the vaccinated person
        last_name (str): surname of the vaccindate person
        birthdate (str): birthday of the vaccinated person in YYYY-MM-DD format
        **vaccination (str): vaccination information as date=manufacturer 

    Return: None
    """
    qr_code = QRCode(
        name=f"{first_name} {last_name}",
        birth=birthdate,
        vaccination=[
            Vaccination(manufacturer=manufacturer, date=datetime.strptime(date, "%Y-%m-%d"))
            for date, manufacturer in vaccination.items()
        ],
    )
    res = requests.get(
        f"http://api.qrserver.com/v1/create-qr-code/?data={qr_code}", stream=True
    )
    if res.status_code != 200:
        raise Exception("QR code cannot be generated by QR Code Generator API.")
    with open("qr_code.png", "wb") as f:
        res.raw.decode_content = True
        shutil.copyfileobj(res.raw, f)
    print("QR code has been generated.")
